-- Criação da tabela de usuários
CREATE TABLE t_agrocare_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    phone_number VARCHAR2(20) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    avatar VARCHAR2(255),
    role VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Criação da tabela de veterinários
CREATE TABLE t_agrocare_veterinario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    phone_number VARCHAR2(20) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    avatar VARCHAR2(255),
    role VARCHAR2(50) NOT NULL,
    especializacao_veterinario VARCHAR2(255) NOT NULL,
    cmrv VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Criação da tabela de animais
CREATE TABLE t_agrocare_animals (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    especie VARCHAR2(255) NOT NULL,
    idade NUMBER NOT NULL,
    peso NUMBER(10, 2) NOT NULL,
    url_image VARCHAR2(255),
    user_id NUMBER,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES t_agrocare_users(id)
);

-- Criação da tabela de serviços
CREATE TABLE t_agrocare_servico (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_servico DATE NOT NULL,
    preco_servico NUMBER(10, 2) NOT NULL,
    diagnostico VARCHAR2(255) NOT NULL,
    user_id NUMBER,
    animal_id NUMBER,
    veterinario_id NUMBER,
    CONSTRAINT fk_user_servico FOREIGN KEY (user_id) REFERENCES t_agrocare_users(id),
    CONSTRAINT fk_animal FOREIGN KEY (animal_id) REFERENCES t_agrocare_animals(id),
    CONSTRAINT fk_veterinario FOREIGN KEY (veterinario_id) REFERENCES t_agrocare_veterinario(id)
);


-- Inserção de usuários
INSERT INTO t_agrocare_users (name, phone_number, email, password, avatar, role) VALUES
('Alice Smith', '+5511999999999', 'alice.smith@example.com', '$2a$12$abc123', 'https://avatar.iran.liara.run/username?username=Alice+Smith', 'ROLE_USER');

INSERT INTO t_agrocare_users (name, phone_number, email, password, avatar, role) VALUES
('Bob Johnson', '+5511988888888', 'bob.johnson@example.com', '$2a$12$abc123', 'https://avatar.iran.liara.run/username?username=Bob+Johnson', 'ROLE_USER');

INSERT INTO t_agrocare_users (name, phone_number, email, password, avatar, role) VALUES
('Carlos Mendes', '+5511911111111', 'carlos.mendes@example.com', '$2a$12$abc124', 'https://avatar.iran.liara.run/username?username=Carlos+Mendes', 'ROLE_USER');

INSERT INTO t_agrocare_users (name, phone_number, email, password, avatar, role) VALUES
('Daniela Silva', '+5511922222222', 'daniela.silva@example.com', '$2a$12$abc125', 'https://avatar.iran.liara.run/username?username=Daniela+Silva', 'ROLE_USER');

INSERT INTO t_agrocare_users (name, phone_number, email, password, avatar, role) VALUES
('Eduardo Lopes', '+5511933333333', 'eduardo.lopes@example.com', '$2a$12$abc126', 'https://avatar.iran.liara.run/username?username=Eduardo+Lopes', 'ROLE_USER');



-- Inserção de veterinários
INSERT INTO t_agrocare_veterinario (name, phone_number, email, password, avatar, role, especializacao_veterinario, cmrv) VALUES
('Dr. Lizier Vet', '+5511999991234', 'leo.vet@example.com', '$2a$12$abc123', 'https://avatar.iran.liara.run/username?username=Leo+Vet', 'ROLE_VET', 'Cirurgião', '12345');

INSERT INTO t_agrocare_veterinario (name, phone_number, email, password, avatar, role, especializacao_veterinario, cmrv) VALUES
('Dr. Emma Vet', '+5511988884321', 'emma.vet@example.com', '$2a$12$abc123', 'https://avatar.iran.liara.run/username?username=Emma+Vet', 'ROLE_VET', 'Dermatologista', '23456');

INSERT INTO t_agrocare_veterinario (name, phone_number, email, password, avatar, role, especializacao_veterinario, cmrv) VALUES
('Dr. Fabio Vet', '+5511944444444', 'fabio.vet@example.com', '$2a$12$abc127', 'https://avatar.iran.liara.run/username?username=Fabio+Vet', 'ROLE_VET', 'Cardiologista', '34567');

INSERT INTO t_agrocare_veterinario (name, phone_number, email, password, avatar, role, especializacao_veterinario, cmrv) VALUES
('Dr. Gabriela Vet', '+5511955555555', 'gabriela.vet@example.com', '$2a$12$abc128', 'https://avatar.iran.liara.run/username?username=Gabriela+Vet', 'ROLE_VET', 'Neurologista', '45678');

INSERT INTO t_agrocare_veterinario (name, phone_number, email, password, avatar, role, especializacao_veterinario, cmrv) VALUES
('Dr. Henrique Vet', '+5511966666666', 'henrique.vet@example.com', '$2a$12$abc129', 'https://avatar.iran.liara.run/username?username=Henrique+Vet', 'ROLE_VET', 'Ortopedista', '56789');


-- Inserção de animais (apenas bovinos)
INSERT INTO t_agrocare_animals (nome, especie, idade, peso, url_image, user_id) VALUES
('Bovino A', 'Bovino', 3, 500.0, 'https://example.com/bovino_a.png', 2);

INSERT INTO t_agrocare_animals (nome, especie, idade, peso, url_image, user_id) VALUES
('Bovino B', 'Bovino', 5, 600.0, 'https://example.com/bovino_b.png', 2);

INSERT INTO t_agrocare_animals (nome, especie, idade, peso, url_image, user_id) VALUES
('Bovino C', 'Bovino', 4, 550.0, 'https://example.com/bovino_c.png', 1);

INSERT INTO t_agrocare_animals (nome, especie, idade, peso, url_image, user_id) VALUES
('Bovino D', 'Bovino', 6, 650.0, 'https://example.com/bovino_d.png', 2);

INSERT INTO t_agrocare_animals (nome, especie, idade, peso, url_image, user_id) VALUES
('Bovino E', 'Bovino', 7, 700.0, 'https://example.com/bovino_e.png', 1);


-- Inserção de serviços
INSERT INTO t_agrocare_servico (data_servico, preco_servico, diagnostico, user_id, animal_id, veterinario_id) VALUES
(TO_DATE('2024-09-01', 'YYYY-MM-DD'), 350.00, 'Tratamento de parasitas', 1, 1, 1);

INSERT INTO t_agrocare_servico (data_servico, preco_servico, diagnostico, user_id, animal_id, veterinario_id) VALUES
(TO_DATE('2024-09-05', 'YYYY-MM-DD'), 500.00, 'Consulta de rotina', 2, 2, 2);

INSERT INTO t_agrocare_servico (data_servico, preco_servico, diagnostico, user_id, animal_id, veterinario_id) VALUES
(TO_DATE('2024-09-07', 'YYYY-MM-DD'), 400.00, 'Vacinação', 1, 3, 1);

INSERT INTO t_agrocare_servico (data_servico, preco_servico, diagnostico, user_id, animal_id, veterinario_id) VALUES
(TO_DATE('2024-09-10', 'YYYY-MM-DD'), 600.00, 'Tratamento ortopédico', 2, 4, 3);

INSERT INTO t_agrocare_servico (data_servico, preco_servico, diagnostico, user_id, animal_id, veterinario_id) VALUES
(TO_DATE('2024-09-15', 'YYYY-MM-DD'), 750.00, 'Exame cardiológico', 1, 5, 2);

-- Update de usuário
UPDATE t_agrocare_users 
SET 
    phone_number = '+5511988887777', 
    email = 'bob.newemail@example.com', 
    avatar = 'https://avatar.iran.liara.run/username?username=Bob+NewName', 
    role = 'ROLE_MODERATOR' 
WHERE email = 'bob.johnson@example.com';


--Update de veterinário
UPDATE t_agrocare_veterinario 
SET 
    phone_number = '+5511999995678', 
    email = 'leo.newemail@example.com', 
    avatar = 'https://avatar.iran.liara.run/username?username=Leo+NewName', 
    especializacao_veterinario = 'Ortopedista', 
    cmrv = '67890' 
WHERE email = 'leo.vet@example.com';


--Update de animais
UPDATE t_agrocare_animals 
SET nome = 'Bovino C' ,
    idade = 6, 
    peso = 620.0, 
    url_image = 'https://example.com/bovino_b_updated.png' 
WHERE nome = 'Bovino B';


--Update de serviço
UPDATE t_agrocare_servico 
SET 
    preco_servico = 360.00, 
    diagnostico = 'Tratamento de parasitas atualizado' 
WHERE data_servico = TO_DATE('2024-09-01', 'YYYY-MM-DD') AND animal_id = 1 AND veterinario_id = 1;


--Delete de usuário
DELETE FROM T_AGROCARE_USERS
WHERE ID = 2;


--Delete de veterinário
DELETE FROM T_AGROCARE_VETERINARIO
WHERE ID = 2;


--Delete de animais
DELETE FROM T_AGROCARE_ANIMALS
WHERE ID = 1;


--Delete de serviço
DELETE FROM T_AGROCARE_SERVICO
WHERE ID = 1;



SELECT 
    a.nome AS animal_nome,
    a.especie AS animal_especie,
    a.idade AS animal_idade,
    a.peso AS animal_peso,
    s.data_servico AS servico_data,
    s.preco_servico AS servico_preco,
    s.diagnostico AS servico_diagnostico
FROM 
    t_agrocare_animals a
JOIN 
    t_agrocare_servico s
ON 
    a.id = s.animal_id
WHERE 
    a.especie = 'Bovino';
    
----------------------------------------------------------
-- Movimentação 1: Atualização de usuários
UPDATE t_agrocare_users 
SET 
    phone_number = '+5511977777777', 
    email = 'alice.updated@example.com', 
    avatar = 'https://avatar.iran.liara.run/username?username=Alice+Updated', 
    role = 'ROLE_ADMIN' 
WHERE id = 1;

-- Movimentação 2: Atualização de veterinários
UPDATE t_agrocare_veterinario 
SET 
    phone_number = '+5511955551234', 
    email = 'emma.updatedvet@example.com', 
    especializacao_veterinario = 'Oncologista',
    cmrv = '34567' 
WHERE id = 2;

-- Movimentação 3: Atualização de animais
UPDATE t_agrocare_animals 
SET 
    nome = 'Bovino F', 
    idade = 4, 
    peso = 580.0, 
    url_image = 'https://example.com/bovino_f_updated.png' 
WHERE id = 3;

-- Movimentação 4: Atualização de serviços
UPDATE t_agrocare_servico 
SET 
    preco_servico = 450.00, 
    diagnostico = 'Vacinação atualizada' 
WHERE id = 3;

-- Movimentação 5: Inserção de novo serviço
INSERT INTO t_agrocare_servico (data_servico, preco_servico, diagnostico, user_id, animal_id, veterinario_id) 
VALUES (TO_DATE('2024-09-20', 'YYYY-MM-DD'), 550.00, 'Consulta Neurológica', 1, 5, 2);


-- Consulta baseado nessas 5 movimentações
SELECT 
    u.name AS usuario_nome,
    u.email AS usuario_email,
    u.phone_number AS usuario_telefone,
    v.name AS veterinario_nome,
    v.email AS veterinario_email,
    v.especializacao_veterinario AS veterinario_especializacao,
    a.nome AS animal_nome,
    a.idade AS animal_idade,
    a.peso AS animal_peso,
    s.data_servico AS servico_data,
    s.preco_servico AS servico_preco,
    s.diagnostico AS servico_diagnostico
FROM 
    t_agrocare_users u
JOIN 
    t_agrocare_servico s ON u.id = s.user_id
JOIN 
    t_agrocare_animals a ON s.animal_id = a.id
JOIN 
    t_agrocare_veterinario v ON s.veterinario_id = v.id
WHERE 
    s.data_servico BETWEEN TO_DATE('2024-09-01', 'YYYY-MM-DD') AND TO_DATE('2024-09-30', 'YYYY-MM-DD');

